import { useEffect, useState, type FormEvent } from 'react'
import { Menu, Volume2, VolumeX, ArrowDown, ExternalLink } from 'lucide-react'
import PixelScorpion from './components/PixelScorpion'
import { replies } from './data/terminal'

const nav = [['WORLD','world'],['LORE','lore'],['SWARM','swarm'],['TOKEN','token']]
const lore = [['01','AWAKEN','A signal stirs beneath the dunes.'],['02','HUNT','Footprints vanish before sunrise.'],['03','STING','One flash in the dark. Then nothing.'],['04','SWARM','The sand is moving.'],['05','???','The desert keeps its secrets.']]
const whispers = ['lurking','watching','waiting','stinging','still here']
const commands = ['help','status','lore','scorp','clear']

function App() {
  const [menuOpen,setMenuOpen]=useState(false), [sound,setSound]=useState(false), [input,setInput]=useState(''), [history,setHistory]=useState<string[]>([]), [boot,setBoot]=useState(0), [mouse,setMouse]=useState({x:0,y:0})
  useEffect(()=>{const timer=window.setTimeout(()=>setBoot(1),250); const onMove=(e:MouseEvent)=>setMouse({x:(e.clientX/window.innerWidth-.5)*10,y:(e.clientY/window.innerHeight-.5)*8});window.addEventListener('mousemove',onMove);return()=>{window.clearTimeout(timer);window.removeEventListener('mousemove',onMove)}},[])
  function submit(e:FormEvent){e.preventDefault();const cmd=input.trim().toLowerCase();if(!cmd)return;if(cmd==='clear'){setHistory([]);setInput('');return}setHistory(h=>[...h,`> ${cmd}`,replies[cmd]??'UNKNOWN COMMAND. TYPE “HELP”.']);setInput('')}
  return <main>
    <div className="crt" aria-hidden="true"/>
    <header className="nav"><a className="brand" href="#top"><span className="mini-mark"><PixelScorpion small/></span><span>SCORP<span className="brand-dot">.</span></span></a><nav className={menuOpen?'nav-links open':'nav-links'}>{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{label}</a>)}<a href="#footer" onClick={()=>setMenuOpen(false)}>X <ExternalLink size={11}/></a><a href="#footer" onClick={()=>setMenuOpen(false)}>TELEGRAM <ExternalLink size={11}/></a></nav><button className="menu-button" aria-label="Toggle navigation" onClick={()=>setMenuOpen(!menuOpen)}><Menu/></button></header>
    <section className="hero" id="top"><div className="hero-stars" style={{transform:`translate(${mouse.x*.18}px,${mouse.y*.18}px)`}}/>
      <div className="moon"/><div className="hero-content"><div className="eyebrow"><span className="live-dot"/> DIGITAL DESERT // UNKNOWN SECTOR</div><h1>SCORP</h1><p className="tagline">THE DESERT IS WATCHING.</p><p className="hero-copy">A pixel creature.<br/>A digital desert.<br/>One sting.</p><div className="hero-actions"><a className="pixel-button primary" href="#world">ENTER THE DESERT <ArrowDown size={14}/></a><a className="pixel-button ghost" href="#footer">VIEW ON X <ExternalLink size={13}/></a></div><span className="hero-coordinate">34° 08′ N &nbsp; / &nbsp; 116° 18′ W</span></div>
      <div className="hero-creature" style={{transform:`translate(${mouse.x*.35}px,${mouse.y*.24}px)`}}><div className="creature-glow"/><PixelScorpion/><span className="creature-label">FIG. 001 — UNCATALOGUED</span></div>
      <div className="dune dune-back"/><div className="dune dune-front"/><div className="hero-ground"/><span className="hero-side-label">KEEP YOUR DISTANCE</span><span className="scroll-hint">SCROLL TO DESCEND <span>↓</span></span><div className="hero-status"><span>SECTOR 09</span><span>● SIGNAL FOUND</span></div>
    </section>
    <section className="world section" id="world"><div className="section-kicker">01 — ARRIVAL LOG</div><div className="section-heading"><h2>WELCOME TO<br/><em>THE DESERT</em></h2><p className="mono small">AN ACCOUNT OF THE UNACCOUNTED</p></div><div className="world-panel"><div className="world-scene"><div className="world-sun"/><div className="world-star s1"/><div className="world-star s2"/><div className="world-dune wd1"/><div className="world-dune wd2"/><div className="world-groundline"/><div className="world-scorp"><PixelScorpion small/></div><button className="discover rock" title="Nothing here" onClick={e=>{e.currentTarget.dataset.tip='NOTHING HERE.'}}>◆</button><button className="discover skull" title="You shouldn't be here" onClick={e=>{e.currentTarget.dataset.tip="YOU SHOULDN'T BE HERE."}}>☠</button><span className="track-mark">•• ▰ ▰ ••</span><span className="scene-coord">DUNE 004 // 02:17 AM</span></div><div className="world-copy"><span className="stamp">FIELD NOTE 001</span><p>Nobody knows where SCORP came from.</p><p>Some say it crawled out of an abandoned server. Some say it was buried beneath the desert.</p><p className="last-line">Others say it has always been here.<br/><em>Waiting.</em></p><div className="note-rule"/><span className="mono small">[ SIGNAL STRENGTH: UNSTABLE ]</span></div></div></section>
    <section className="lore section" id="lore"><div className="section-kicker">02 — FRAGMENTED RECORD</div><div className="section-heading"><h2>THE <em>STING</em></h2><p className="mono small">FIVE FRAMES FROM A LOST CARTRIDGE</p></div><div className="timeline">{lore.map(([n,title,desc],i)=><article className="timeline-step" key={n}><div className="step-image"><span className="step-number">{n}</span><span className="step-sun"/><span className="step-dune"/>{i>1&&<div className="step-scorp"><PixelScorpion small/></div>}<span className="step-state">{i===4?'SIGNAL LOST':'MEMORY FRAGMENT'}</span></div><div className="step-copy"><span className="mono small">FRAME {n}</span><h3>{title}</h3><p>{desc}</p></div>{i<4&&<span className="step-connector">············▶</span>}</article>)}</div></section>
    <section className="character section" id="character"><div className="section-kicker">03 — SPECIMEN FILE</div><div className="section-heading"><h2>MEET <em>SCORP</em></h2><p className="mono small">DO NOT ATTEMPT TO HANDLE</p></div><div className="character-card"><div className="character-visual"><div className="scan-circle"/><div className="character-aura"/><PixelScorpion/><span className="specimen-id">SCP—0001</span><span className="measure measure-x"/><span className="measure measure-y"/></div><div className="character-info"><div className="classification"><span>CLASSIFICATION</span><b>UNKNOWN / ACTIVE</b></div><div className="stat-grid">{[['SPECIES','UNKNOWN'],['HABITAT','THE DESERT'],['TEMPER','UNSTABLE'],['STATUS','AWAKE']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="warning-note">! &nbsp; EYES MAY BE FOLLOWING YOU</div><p className="mono small muted">TEMPORARY PIXEL SPECIMEN // FINAL MASCOT PENDING</p></div></div></section>
    <section className="swarm section" id="swarm"><div className="section-kicker">04 — POPULATION REPORT</div><div className="section-heading"><h2>THE <em>SWARM</em></h2><p className="mono small">YOU ARE NOT ALONE OUT HERE</p></div><div className="swarm-layout"><div className="swarm-intro"><p>One scorpion is nothing.</p><p className="swarm-big">A swarm<br/>is <em>different.</em></p><div className="swarm-actions"><a href="#footer" className="pixel-button primary">JOIN TELEGRAM <ExternalLink size={13}/></a><a href="#footer" className="pixel-button ghost">FOLLOW X <ExternalLink size={13}/></a></div></div><div className="swarm-board"><div className="board-head"><span>NEARBY SIGNALS</span><span>LIVE // {String(64).padStart(2,'0')}</span></div><div className="swarm-grid">{Array.from({length:64},(_,i)=><div className={`swarm-cell ${[1,4,8,11,16,19,23,25,29,32,37,40,42,47,50,54,58,61].includes(i)?'active':''}`} key={i} title={whispers[i%whispers.length]}><PixelScorpion small/></div>)}</div><div className="board-foot"><span>18 ACTIVE</span><span>THE REST ARE LISTENING</span></div></div></div></section>
    <section className="token section" id="token"><div className="section-kicker">05 — ARTIFACT RECORD</div><div className="section-heading"><h2>THE <em>STING</em></h2><p className="mono small">DETAILS WILL SURFACE WHEN THEY SURFACE</p></div><div className="token-card"><div className="token-title"><span className="token-glyph">✳</span><div><span className="mono small">FOUND OBJECT</span><h3>$SCORP</h3></div><span className="token-index">ARTIFACT / 001</span></div><div className="token-data"><div><span>TICKER</span><b>$SCORP</b></div><div><span>NETWORK</span><b>SOLANA</b></div><div><span>CONTRACT</span><b className="pending">COMING SOON</b></div><div><span>SUPPLY</span><b className="pending">COMING SOON</b></div></div><div className="token-warning">NO PROMISES.<br/>NO PROPHECY.<br/><em>JUST SCORP.</em></div></div></section>
    <section className="roadmap section"><div className="section-kicker">06 — EXPEDITION MAP</div><div className="section-heading"><h2>NO <em>KNOWN END</em></h2><p className="mono small">THE PATH MAY CHANGE</p></div><div className="map-path">{[['LEVEL 01','AWAKEN',['Website','Socials','Community']],['LEVEL 02','HUNT',['Launch','Community growth','Pixel world expansion']],['LEVEL 03','STING',['Lore expansion','Interactive features','Community events']],['LEVEL 04','SWARM',['???','???','???']]].map(([level,title,items],i)=><article className={`map-level level-${i+1}`} key={String(level)}><div className="map-node">{String(i+1).padStart(2,'0')}</div><span className="mono small">{level as string}</span><h3>{title as string}</h3><ul>{(items as string[]).map(item=><li key={item}><i/>{item}</li>)}</ul>{i<3&&<span className="map-dashes">━━━━━╲</span>}</article>)}</div></section>
    <section className="terminal-section section"><div className="section-kicker">07 — UNSANCTIONED ACCESS</div><div className="section-heading"><h2>SCORP <em>// TERMINAL</em></h2><p className="mono small">LOCAL CONNECTION // NO TRACE</p></div><div className="terminal-window"><div className="terminal-bar"><span className="terminal-lights"><i/><i/><i/></span><span>SCORP_SYS://DESERT_NODE_01</span><span className="terminal-live">● CONNECTED</span></div><div className="terminal-body"><div className="boot-text">{(boot?['> initializing desert...','> scanning dunes...','> locating creature...','','> FOUND.','','> SCORP IS AWAKE.']:[]).map((line,i)=><div key={i} className={i===6?'terminal-found':''}>{line}</div>)}</div>{history.map((line,i)=><div className={i%2===0?'terminal-command':'terminal-response'} key={i}>{line}</div>)}<form onSubmit={submit} className="terminal-form"><label htmlFor="terminal-input">&gt;</label><input id="terminal-input" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off" spellCheck="false" aria-label="Terminal command"/><span className="cursor"/></form><div className="terminal-hints">{commands.map(c=><button key={c} onClick={()=>c==='clear'?setHistory([]):(setInput(c),document.getElementById('terminal-input')?.focus())}>{c}</button>)}</div></div></div></section>
    <footer id="footer"><div className="footer-brand"><span className="mini-mark"><PixelScorpion small/></span><div><b>SCORP</b><span>THE DESERT IS WATCHING.</span></div></div><div className="footer-links"><a href="#footer">X <ExternalLink size={11}/></a><a href="#footer">TELEGRAM <ExternalLink size={11}/></a><button onClick={()=>setSound(!sound)} aria-label="Toggle ambient sound"><span className={sound?'sound-on':''}>{sound?<Volume2 size={15}/>:<VolumeX size={15}/>}</span> SOUND {sound?'ON':'OFF'}</button></div><span className="copyright">© 2026 SCORP</span><span className="footer-coord">SIGNAL WILL RETURN</span></footer>
  </main>
}
export default App
